# Métodos numéricos Tarea 11

### Pregunta 1

In [1]:
%load_ext autoreload

In [2]:
%autoreload 2
import numpy as np
from src import gauss_jacobi, gauss_seidel

A_a = np.array([
    [3, -1, 1],
    [3, 6, 2],
    [3, 3, 7]
])

b_a = np.array([1, 0, 4])

A_b = np.array([
    [10, -1, 0],
    [-1, 10, -2],
    [0, -2, 10]
])

b_b = np.array([9, 7, 6])

A_c = np.array([
    [10, 5, 0, 0],
    [5, 10, -4, 0],
    [0, -4, 8, -1],
    [0, 0, -1, 5]
])

b_c = np.array([6, 25, -11, -11])

A_d = np.array([
    [4, 1, 1, 0, 1],
    [-1, -3, 1, 1, 0],
    [2, 1, 5, -1, -1],
    [-1, 0, -1, 4, 0],
    [0, 2, -1, 1, 4]
])

b_d = np.array([6, 6, 6, 6, 6])


[08-14 01:58:30][INFO] 2024-08-14 01:58:30.919715


In [3]:
# Condiciones iniciales
x0 = np.zeros_like(b_a, dtype=float)

# Realizar las primeras dos iteraciones usando Jacobi
x_jacobi, tray_jacobi = gauss_jacobi(A=A_a, b=b_a, x0=x0, tol=1e-5, max_iter=2)

print(tray_jacobi)

[array([0., 0., 0.]), array([[0.33333333],
       [0.        ],
       [0.57142857]])]


In [4]:
# Condiciones iniciales
x0 = np.zeros_like(b_b, dtype=float)

# Realizar las primeras dos iteraciones usando Jacobi
x_jacobi, tray_jacobi = gauss_jacobi(A=A_b, b=b_b, x0=x0, tol=1e-5, max_iter=2)

print(tray_jacobi)

[array([0., 0., 0.]), array([[0.9],
       [0.7],
       [0.6]])]


In [5]:
# Condiciones iniciales
x0 = np.zeros_like(b_c, dtype=float)

# Realizar las primeras dos iteraciones usando Jacobi
x_jacobi, tray_jacobi = gauss_jacobi(A=A_c, b=b_c, x0=x0, tol=1e-5, max_iter=2)

print(tray_jacobi)

[array([0., 0., 0., 0.]), array([[ 0.6  ],
       [ 2.5  ],
       [-1.375],
       [-2.2  ]])]


In [6]:
# Condiciones iniciales
x0 = np.zeros_like(b_d, dtype=float)

# Realizar las primeras dos iteraciones usando Jacobi
x_jacobi, tray_jacobi = gauss_jacobi(A=A_d, b=b_d, x0=x0, tol=1e-5, max_iter=2)

print(tray_jacobi)

[array([0., 0., 0., 0., 0.]), array([[ 1.5],
       [-2. ],
       [ 1.2],
       [ 1.5],
       [ 1.5]])]


### Pregunta 2

In [7]:
# A
x0 = np.zeros_like(b_a, dtype=float)
x_seidel, tray_seidel = gauss_seidel(A=A_a, b=b_a, x0=x0, tol=1e-5, max_iter=2)
print(tray_seidel)

[array([0., 0., 0.]), array([[ 0.33333333],
       [-0.16666667],
       [ 0.5       ]])]


In [8]:
# B
x0 = np.zeros_like(b_b, dtype=float)
x_seidel, tray_seidel = gauss_seidel(A=A_b, b=b_b, x0=x0, tol=1e-5, max_iter=2)
print(tray_seidel)

[array([0., 0., 0.]), array([[0.9  ],
       [0.79 ],
       [0.758]])]


In [9]:
# C
x0 = np.zeros_like(b_c, dtype=float)
x_seidel, tray_seidel = gauss_seidel(A=A_c, b=b_c, x0=x0, tol=1e-5, max_iter=2)
print(tray_seidel)

[array([0., 0., 0., 0.]), array([[ 0.6  ],
       [ 2.2  ],
       [-0.275],
       [-2.255]])]


In [10]:
# D
x0 = np.zeros_like(b_d, dtype=float)
x_seidel, tray_seidel = gauss_seidel(A=A_d, b=b_d, x0=x0, tol=1e-5, max_iter=2)
print(tray_seidel)

[array([0., 0., 0., 0., 0.]), array([[ 1.5   ],
       [-2.5   ],
       [ 1.1   ],
       [ 2.15  ],
       [ 2.4875]])]


### Pregunta 3

In [11]:
# Condiciones iniciales
x0 = np.zeros_like(b_a, dtype=float)
x_jacobi, tray_jacobi = gauss_jacobi(A=A_a, b=b_a, x0=x0, tol=1e-3, max_iter=2)
print(tray_jacobi)

[array([0., 0., 0.]), array([[0.33333333],
       [0.        ],
       [0.57142857]])]


In [12]:
# Condiciones iniciales
x0 = np.zeros_like(b_b, dtype=float)
x_jacobi, tray_jacobi = gauss_jacobi(A=A_b, b=b_b, x0=x0, tol=1e-3, max_iter=2)
print(tray_jacobi)

[array([0., 0., 0.]), array([[0.9],
       [0.7],
       [0.6]])]


In [13]:
# Condiciones iniciales
x0 = np.zeros_like(b_c, dtype=float)
x_jacobi, tray_jacobi = gauss_jacobi(A=A_c, b=b_c, x0=x0, tol=1e-3, max_iter=2)
print(tray_jacobi)

[array([0., 0., 0., 0.]), array([[ 0.6  ],
       [ 2.5  ],
       [-1.375],
       [-2.2  ]])]


In [14]:
# Condiciones iniciales
x0 = np.zeros_like(b_d, dtype=float)
x_jacobi, tray_jacobi = gauss_jacobi(A=A_d, b=b_d, x0=x0, tol=1e-3, max_iter=2)
print(tray_jacobi)

[array([0., 0., 0., 0., 0.]), array([[ 1.5],
       [-2. ],
       [ 1.2],
       [ 1.5],
       [ 1.5]])]


### Pregunta 4

In [15]:
# A
x0 = np.zeros_like(b_a, dtype=float)
x_seidel, tray_seidel = gauss_seidel(A=A_a, b=b_a, x0=x0, tol=1e-3, max_iter=2)
print(tray_seidel)

[array([0., 0., 0.]), array([[ 0.33333333],
       [-0.16666667],
       [ 0.5       ]])]


In [16]:
# B
x0 = np.zeros_like(b_b, dtype=float)
x_seidel, tray_seidel = gauss_seidel(A=A_b, b=b_b, x0=x0, tol=1e-3, max_iter=2)
print(tray_seidel)

[array([0., 0., 0.]), array([[0.9  ],
       [0.79 ],
       [0.758]])]


In [17]:
# C
x0 = np.zeros_like(b_c, dtype=float)
x_seidel, tray_seidel = gauss_seidel(A=A_c, b=b_c, x0=x0, tol=1e-3, max_iter=2)
print(tray_seidel)

[array([0., 0., 0., 0.]), array([[ 0.6  ],
       [ 2.2  ],
       [-0.275],
       [-2.255]])]


In [18]:
# D
x0 = np.zeros_like(b_d, dtype=float)
x_seidel, tray_seidel = gauss_seidel(A=A_d, b=b_d, x0=x0, tol=1e-3, max_iter=2)
print(tray_seidel)

[array([0., 0., 0., 0., 0.]), array([[ 1.5   ],
       [-2.5   ],
       [ 1.1   ],
       [ 2.15  ],
       [ 2.4875]])]


### Pregunta 5

In [19]:
A = np.array([
    [2, -1, 1],
    [2, 2, 2],
    [-1, -1, 2]
])

b = np.array([-1, 4, -5])

In [20]:
# Literal A
x0 = np.zeros_like(b, dtype=float)
x_jacobi, tray_jacobi = gauss_jacobi(A=A, b=b, x0=x0, tol=1e-5, max_iter=25)
print(tray_jacobi[24])

[[ -7.73114914]
 [-32.92459655]
 [  7.73114914]]


In [21]:
# Literal B
x0 = np.zeros_like(b, dtype=float)
x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=1e-5, max_iter=40)
print(tray_seidel[len(tray_seidel)-1], len(tray_seidel))

[[ 0.99999571]
 [ 2.00000477]
 [-0.99999976]] 23


### Pregunta 6

In [22]:
A = np.array([
    [1, 0, -1],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
])

b = np.array([0.2, -1.425, 2])

**Literal a)**</br>

Verificamos si para cada fila, el valor absoluto del elemento de la diagonal es mayor que la suma de los valores absolutos de los otros elementos en esa fila:

Primer  fila |1| >    |0| +    |1| -> 1 > 1    -> No es dominante </br>
Segunda fila |1| > |-1/2| + |-1/4| -> 1 > 0.75 -> Es dominante    </br>
Tercera fila |1| >    |1| + |-1/2| -> 1 > 1.5  -> No es dominante </br>

In [26]:
# Literal B
x0 = np.zeros_like(b, dtype=float)
x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=1e-22, max_iter=300)
print(tray_seidel[len(tray_seidel)-1], len(tray_seidel))

[[ 0.9]
 [-0.8]
 [ 0.7]] 300


In [27]:
# Literal C
A = np.array([
    [1, 0, -2],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
])

b = np.array([0.2, -1.425, 2])

In [34]:
x0 = np.zeros_like(b, dtype=float)
x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=1e-22, max_iter=300)
print(tray_seidel[len(tray_seidel)-1], len(tray_seidel))

[[-1.56863478e+41]
 [-9.80396739e+40]
 [ 1.07843641e+41]] 300


### Pregunta 7

In [29]:
A = np.array([
    [1, 0, -1],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
])

b = np.array([0.2, -1.425, 2])

In [30]:
# Literal B
x0 = np.zeros_like(b, dtype=float)
x_seidel, tray_seidel = gauss_jacobi(A=A, b=b, x0=x0, tol=1e-22, max_iter=300)
print(tray_seidel[len(tray_seidel)-1], len(tray_seidel))

[[ 0.89979164]
 [-0.80015806]
 [ 0.70025541]] 300


In [31]:
# Literal C
A = np.array([
    [1, 0, -2],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
])

b = np.array([0.2, -1.425, 2])

In [32]:
x0 = np.zeros_like(b, dtype=float)
x_seidel, tray_seidel = gauss_jacobi(A=A, b=b, x0=x0, tol=1e-22, max_iter=300)
print(tray_seidel[len(tray_seidel)-1], len(tray_seidel))

[[-1.79225360e+43]
 [-4.51500391e+42]
 [ 6.72394565e+42]] 300


### Pregunta 8

In [35]:
# Matriz de coeficientes A
A = np.array([
    [4, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
    [-1, 4, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0],
    [0, -1, 4, -1, 0, 0, -1, 0, 0, 0, 0, 0],
    [0, 0, -1, 4, 0, 0, 0, -1, 0, 0, 0, 0],
    [-1, 0, 0, 0, 4, -1, 0, 0, -1, 0, 0, 0],
    [0, -1, 0, 0, -1, 4, -1, 0, 0, -1, 0, 0],
    [0, 0, -1, 0, 0, -1, 4, -1, 0, 0, -1, 0],
    [0, 0, 0, -1, 0, 0, -1, 4, 0, 0, 0, -1],
    [0, 0, 0, 0, -1, 0, 0, 0, 4, -1, 0, 0],
    [0, 0, 0, 0, 0, -1, 0, 0, -1, 4, -1, 0],
    [0, 0, 0, 0, 0, 0, -1, 0, 0, -1, 4, -1],
    [0, 0, 0, 0, 0, 0, 0, -1, 0, 0, -1, 4]
])

# Vector de términos independientes b
b = np.array([220, 110, 110, 220, 110, 110, 110, 110, 220, 110, 110, 220])

In [36]:
# Literal B
x0 = np.zeros_like(b, dtype=float)
x_seidel, tray_seidel = gauss_jacobi(A=A, b=b, x0=x0, tol=1e-2, max_iter=30)
print(tray_seidel[len(tray_seidel)-1], len(tray_seidel))

[[120.81717779]
 [133.19430534]
 [133.19430534]
 [120.81717779]
 [130.10139887]
 [168.80941421]
 [168.80941421]
 [130.10139887]
 [120.81717779]
 [133.19430534]
 [133.19430534]
 [120.81717779]] 30


In [37]:
# Literal C
x0 = np.zeros_like(b, dtype=float)
x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=1e-2, max_iter=30)
print(tray_seidel[len(tray_seidel)-1], len(tray_seidel))

[[120.83943397]
 [133.23252312]
 [133.23419576]
 [120.84261504]
 [130.13480245]
 [168.86582774]
 [168.86762091]
 [130.13821275]
 [120.84183139]
 [133.23546372]
 [133.23642492]
 [120.84365942]] 20


In [ ]:
120.83943397, 133.23252312, 133.23419576, 120.84261504, 130.13480245, 168.86582774, 168.86762091, 130.13821275, 120.84183139, 133.23546372, 133.23642492, 120.84365942,